#Redis
redis1:
  image: redis:latest
  ports:
    - "6101:6379"
redis2:
  image: redis:latest
  ports:
    - "6102:6379"

twemproxy:
  image: ganomede/twemproxy
  ports:
    - 6379:6379
    - 6222:6222
  links:
    - redis1:a
    - redis2:b
